-- ============================================================================
-- ORGANIZATION LOGO MIGRATION
-- ============================================================================
-- Date: December 3, 2025
-- Description: Add logo support for organizations
-- ============================================================================

-- Add logo columns to organizations table
ALTER TABLE organizations 
ADD COLUMN IF NOT EXISTS logo_url TEXT NULL,
ADD COLUMN IF NOT EXISTS logo_storage_path TEXT NULL;

-- Add comment for documentation
COMMENT ON COLUMN organizations.logo_url IS 'Public URL of the organization logo image';
COMMENT ON COLUMN organizations.logo_storage_path IS 'Storage path in Supabase bucket for logo deletion';

-- ============================================================================
-- SUPABASE STORAGE BUCKET SETUP
-- ============================================================================
-- Run these commands in Supabase Dashboard > Storage or via SQL:
--
-- 1. Create the organization-files bucket:
--    INSERT INTO storage.buckets (id, name, public)
--    VALUES ('organization-files', 'organization-files', true);
--
-- 2. Create storage policies for the bucket:
--
--    -- Allow authenticated users to upload to their organization's folder
--    CREATE POLICY "Organization admins can upload logos"
--    ON storage.objects FOR INSERT
--    TO authenticated
--    WITH CHECK (
--      bucket_id = 'organization-files'
--      AND (storage.foldername(name))[1] IN (
--        SELECT o.id::text FROM organizations o
--        JOIN organization_members om ON o.id = om.organization_id
--        WHERE om.user_id = auth.uid()
--        AND om.role IN ('Owner', 'Admin')
--      )
--    );
--
--    -- Allow anyone to read (public bucket)
--    CREATE POLICY "Anyone can view organization logos"
--    ON storage.objects FOR SELECT
--    TO public
--    USING (bucket_id = 'organization-files');
--
--    -- Allow organization admins to delete logos
--    CREATE POLICY "Organization admins can delete logos"
--    ON storage.objects FOR DELETE
--    TO authenticated
--    USING (
--      bucket_id = 'organization-files'
--      AND (storage.foldername(name))[1] IN (
--        SELECT o.id::text FROM organizations o
--        JOIN organization_members om ON o.id = om.organization_id
--        WHERE om.user_id = auth.uid()
--        AND om.role IN ('Owner', 'Admin')
--      )
--    );
--
--    -- Allow organization admins to update logos
--    CREATE POLICY "Organization admins can update logos"
--    ON storage.objects FOR UPDATE
--    TO authenticated
--    USING (
--      bucket_id = 'organization-files'
--      AND (storage.foldername(name))[1] IN (
--        SELECT o.id::text FROM organizations o
--        JOIN organization_members om ON o.id = om.organization_id
--        WHERE om.user_id = auth.uid()
--        AND om.role IN ('Owner', 'Admin')
--      )
--    );
--
-- ============================================================================

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================
-- Run this to verify the migration was successful:
--
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'organizations' 
-- AND column_name IN ('logo_url', 'logo_storage_path');
--
-- Expected output:
-- logo_url           | text | YES
-- logo_storage_path  | text | YES
-- ============================================================================
